spring:
  application:
    name: CommerceCartAPI


  mongodb:
    host: localhost
    port: 27017
    database: commerce-service
  data:
    redis:
      host: localhost
      port: 6380

  cache:
    redis:
      time-to-live: 60000

platzi:
  client:
    url: https://api.escuelajs.co/api/v1/